version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: invernadero_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invernadero
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: invernadero_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=invernadero

volumes:
  db_data:
